<Project>
    <PropertyGroup>
        <!-- Folder containing SpaceEngineers.exe -->
        <Bin64></Bin64>

        <!-- Folder containing SpaceEngineersDedicated.exe -->
        <DS64></DS64>

        <!-- Plugin Loader folders for automatic deployment -->
        <Pulsar></Pulsar>
        <Magnetar></Magnetar>
        
        <!-- Plugin version -->
        <Version>10.0.0</Version>
        <AssemblyVersion>10.0.5.0</AssemblyVersion>
        <FileVersion>10.0.5.0</FileVersion>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Windows'))">
        <Bin64 Condition="'$(Bin64)' == ''">$(registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 244850@InstallLocation)\Bin64</Bin64>
        <DS64 Condition="'$(DS64)' == ''">$(registry:HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Steam App 298740@InstallLocation)\DedicatedServer64</DS64>
    </PropertyGroup>

    <PropertyGroup Condition="$([MSBuild]::IsOSPlatform('Linux'))">
        <Bin64 Condition="'$(Bin64)' == '' and '$(HOME)' != ''">$(HOME)/.steam/steam/steamapps/common/SpaceEngineers/Bin64</Bin64>
        <DS64 Condition="'$(DS64)' == '' and '$(HOME)' != ''">$(HOME)/.steam/steam/steamapps/common/SpaceEngineersDedicatedServer/DedicatedServer64</DS64>
    </PropertyGroup>
</Project>
